#!/usr/bin/env bash
set -euo pipefail

# Deploy Soroban contracts to Stellar testnet
# Writes contract addresses to contracts.env

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CONTRACTS_DIR="$PROJECT_ROOT/soroban-contracts"
ENV_FILE="$PROJECT_ROOT/contracts.env"

echo "[deploy] Building and deploying Soroban contracts to testnet..."

# Build contracts
echo "[deploy] Building spending-policy..."
cd "$CONTRACTS_DIR/spending-policy"
stellar contract build

echo "[deploy] Building reputation..."
cd "$CONTRACTS_DIR/reputation"
stellar contract build

# Deploy spending-policy
echo "[deploy] Deploying spending-policy..."
cd "$CONTRACTS_DIR/spending-policy"
SPENDING_POLICY_ID=$(stellar contract deploy \
  --wasm target/wasm32-unknown-unknown/release/spending_policy.wasm \
  --network testnet \
  --source "$DEPLOYER_SECRET")

echo "[deploy] SpendingPolicy deployed: $SPENDING_POLICY_ID"

# Deploy reputation
echo "[deploy] Deploying reputation..."
cd "$CONTRACTS_DIR/reputation"
REPUTATION_ID=$(stellar contract deploy \
  --wasm target/wasm32-unknown-unknown/release/reputation.wasm \
  --network testnet \
  --source "$DEPLOYER_SECRET")

echo "[deploy] ReputationRegistry deployed: $REPUTATION_ID"

# Write contract addresses
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/deploy.sh — do not edit manually
SPENDING_POLICY_CONTRACT_ID=$SPENDING_POLICY_ID
REPUTATION_CONTRACT_ID=$REPUTATION_ID
EOF

echo "[deploy] Contract addresses written to contracts.env"
echo "[deploy] Done."
